FROM node:22 AS construccion

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run lint
RUN npm run build

FROM nginx:alpine AS empaquetado

WORKDIR /usr/share/nginx/html

COPY --from=construccion /app/dist .

