
FROM node:22 AS build

WORKDIR /home/taskList_Front

COPY ./ /home/proyecto_taskList

RUN npm install
RUN npm run lint
RUN npm run build

FROM nginx AS publish

WORKDIR /usr/proyecto_taskList/nginx/html

COPY --from=build /home/proyecto_taskList/taskList_front/dist .

